# Generated by Django 4.2.1 on 2023-05-27 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('authentication', '0002_alter_customuser_tg_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='orders.vehicle'),
        ),
    ]
