# Generated by Django 4.2.1 on 2023-05-27 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_customuser_phone_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='machine',
        ),
    ]
