# Generated by Django 4.2.1 on 2023-05-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(blank=True, max_length=50, null=True)),
                ('car_num', models.CharField(max_length=8, unique=True)),
                ('capacity', models.FloatField(default=3.5)),
                ('state', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('SML', 'SMALL'), ('MID', 'MIDDLE'), ('BIG', 'BIG'), ('SPB', 'SUPER BIG')], default='MID', max_length=3)),
            ],
        ),
    ]
