# Generated by Django 4.2.1 on 2023-05-27 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0003_vehicle_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='preorderfromclient',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pre_orders', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
