# Generated by Django 4.2.1 on 2023-05-27 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_preorderfromclient_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='user',
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100)),
                ('phone_num', models.CharField(max_length=13, unique=True)),
                ('tg_username', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='orders.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couped_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.driver')),
                ('pre_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.preorderfromclient')),
            ],
            options={
                'ordering': ['-couped_at'],
                'indexes': [models.Index(fields=['-couped_at'], name='orders_orde_couped__a3c37a_idx')],
            },
        ),
    ]
